#ifndef MODELTABLERTO_GLOBAL_H
#define MODELTABLERTO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODELTABLERTO_LIBRARY)
#  define MODELTABLERTOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODELTABLERTOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TABLERTO_GLOBAL_H
