#ifndef MAPGRAPHICSWIDGET_GLOBAL_H
#define MAPGRAPHICSWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MAPGRAPHICSWIDGET_LIBRARY)
#  define MAPGRAPHICSWIDGET_EXPORT Q_DECL_EXPORT
#else
#  define MAPGRAPHICSWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // MAPGRAPHICSWIDGET_GLOBAL_H
